### ISSUE TITLE
regarding the red led - what wave length should we be using?

### ISSUE THREAD

**Issue by akivato** [Abhijeetbyte/NDVI-GO#3]

**Comment by Abhijeetbyte** [comment]
Hi, @akivato 

Red LED should be 630-700 nm and IR  - 780 -m 1200 nm
I will add it to README too

**Comment by akivato** [comment]
Thanks. 
please can you provide a spec and example for the LDR recommended to buy?

**Comment by Abhijeetbyte** [comment]
I have used **GL5528 (10K-20K / 1M ohm)**

```
Model: GL5528
Maximum Voltage: 150v DC
Maximum Wattage: 100mw
Spectral Peak: 540nm
Light Resistance: 10K to 20K ohm
Dark Resistance: 1M ohm
Response Time (ms): Up: 20/ Down: 30 
Material: Carbon 
Size: 5 x 3mm/0.2 x 0.12" 
```
This is the most common, you can buy it wherever you find it
